name: Build

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  VERBOSE: true

jobs:  
  windows:
    runs-on: windows-latest    
    steps:
      - uses: actions/checkout@v3
      
      - name: Clone submodules
        run: |
          git submodule update --init
          cd cimgui
          git checkout docking_inter
          git submodule update --init
      
      - name: Prepare cimgui
        run: |
          Copy-item -Force -Recurse -Verbose ".\cimgui-deps\*" -Destination ".\cimgui\"
          ((Get-Content .\cimgui\cimgui.cpp -Raw) -replace "#include `"cimgui.h`"","#define CIMGUI_NO_EXPORT`n#include `"cimgui.h`"`n#include <generator/output/cimgui_impl.h>") | Set-Content .\cimgui\cimgui.cpp
      
      - name: Build cimgui
        run: |
          cd .\cimgui\
          cmake .
          cmake --build . --target ALL_BUILD --config Debug -- /nologo /maxcpucount
          cmake --build . --target ALL_BUILD --config Release -- /nologo /maxcpucount
      
      - name: Copy binaries to dist
        run: |
          New-Item -ItemType Directory -Force -Path ".\dist\Debug-Win64\"
          New-Item -ItemType Directory -Force -Path ".\dist\Release-Win64\"
          Copy-item -Force -Verbose ".\cimgui\Debug\cimgui.lib" -Destination ".\dist\Debug-Win64\"
          Copy-item -Force -Verbose ".\cimgui\Release\cimgui.lib" -Destination ".\dist\Release-Win64\"
      
      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist/*              
          git commit -m "Generation"
  merge:
    runs-on: ubuntu-latest
    needs: [windows]
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
          
      - name: Login
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
      - name: Get latest cimgui binding info
        run: |
          git submodule update --init
          cd cimgui
          git checkout docking_inter
          
      - name: Generate ImGui bindings
        run: |
          cd ./Generator/
          dotnet run
          git add ..
          git commit -m "Generate Bindings"
          git push origin master
